### ISSUE TITLE
BUG: Inline Form Dropdown Icons Alignment

### ISSUE THREAD

**Issue by dacodekid** [unfoldadmin/django-unfold#397]
After the new update (0.23.0), the inline dropdown icons are aligning vertically.

![image](https://github.com/unfoldadmin/django-unfold/assets/10047844/08f944c8-09c1-4167-926a-23256d49020a)

**Comment by dacodekid** [comment]
Temp solution:

```css
.related-widget-wrapper {
    display: flex;
    flex-wrap: nowrap;
    align-items: center;
    gap: 5px;
}

.related-widget-wrapper-link {
    display: inline-block;
}
```
